### PR TITLE
add return context, fix tests for additional out parameter

### PR DESCRIPTION
**Pull request by ADone**
for #56 

Signed-off-by: Artem Nistratov <anistratov@go-promo.ru>

### CODE REVIEW

**Comment by arekkas** [comment]
Thanks for the contribution! What's the rational behind returning implicit values? I can see that it gives flexibility but it's nothing short of returning `interface{}` values. What did you try to solve when applying this?

**Comment by ADone** [comment]
Maybe I misunderstood you, but return type is clear. It's `context.Context` and it was created to resolve such issues like share some variables across all execution pipleline. I return a user model associated with added or extracted token, token usage information and some other options. With context I link refresh and access token in PersistAuthorizeCodeGrantSession, because token saving logic already implemented in CreateAccessTokenSession and CreateRefreshTokenSession. I don't want copy&paste it in PersistAuthorizeCodeGrantSession. Instead I put RefreshToken & AccessToken models into new context in its creation functions. I think there are many other suitable variants for return context usage.

**Comment by arekkas** [comment]
Ah sorry, my bad, I misread :)

**Comment by arekkas** [comment]
Sharing data is intended to be happening through `Requester.GetSession() interface{}` / `Requester.SetSession(session interface{})`. That's where you would store user ids and that stuff. Or did I miss something?

**Comment by arekkas** [comment]
Could you maybe show me some usage examples, that would make it easier to understand for me :)

**Comment by arekkas** [comment]
Do you maybe know an example project where contexts are returned as well? I have looked at some go projects but never seen contexts get returned. [Docker](https://github.com/docker/docker/search?p=5&q=context.Context&utf8=%E2%9C%93) for example only returns `context.Context` within `NewSomethingContext()`.

Only because nobody uses it, it doesn't imply that it's not a good idea. However, I need to nullify any doubt of unwanted sideffects or other issues :)

**Comment by ADone** [comment]
I use the `JWT Session` as session interface. Hm, I didn't look at this from this point. May be more preferable to extend JWT session.
In examples I seen only `nil` in session. It is misleading (

**Comment by arekkas** [comment]
Sorry for that. :( Documentation is on my list, but I have a lot to do right now.

Would you maybe be interested in helping here a little bit? Seems like you've already a good picture of how things work!

**Comment by ADone** [comment]
I will try)
Sorry for wasting your time, I close PR.

**Comment by arekkas** [comment]
No worries, I'm sorry that the docs didn't mention that :)

**Pull request closed without merging**
