### PR TITLE
Fix reference to store example

### PR DESCRIPTION
**Pull request by hatchan**

### CODE REVIEW

**Comment by arekkas** [comment]
Thanks! Could you please sign your commit? `git commit --amend -s`

**Comment by arekkas** [comment]
ping @hatchan

**Comment by hatchan** [comment]
Oops sorry. I haven't set it up on this machine. Will take a look at it tonight/this weekend.

**Comment by hatchan** [comment]
@arekkas I've updated the commit

**Comment by arekkas** [comment]
Thanks!

**Pull request merged**
