### PR TITLE
fix jwt strategy interface mismatch

### PR DESCRIPTION
**Pull request by jacyzon**
Validate token function only return error by [interface definition](https://github.com/ory-am/fosite/blob/dfb047d/handler/core/strategy.go), but in jwt strategy return both signature and error.

### CODE REVIEW

**Comment by arekkas** [comment]
thanks!

**Comment by arekkas** [comment]
Please sign the [DCO](https://github.com/ory-am/fosite/blob/master/CONTRIBUTING.md#developers-certificate-of-origin). You can do so with `git commit --amend -s`

**Comment by jacyzon** [comment]
@arekkas  signed =)

**Comment by arekkas** [comment]
thanks!

**Pull request merged**
