### PR TITLE
Request: fix SetRequestedScopes

### PR DESCRIPTION
**Pull request by pschultz**
SetRequestedScopes actually appended.

### CODE REVIEW

**Comment by arekkas** [comment]
thanks! on the road right now, will review tomorrow

Von meinem iPhone gesendet

**Comment by arekkas** [comment]
Thanks!

**Comment by arekkas** [comment]
This is actually a change that introduced regression issues, reverting.

**Comment by arekkas** [comment]
Nevermind my last comment, it introduced a regression issue elsewhere, not reverting.

**Comment by pschultz** [comment]
What comment? Did you mean to write in another PR?

**Comment by arekkas** [comment]
nvm I mistakenly thought a bug is a regression caused by this pr but its not. I deleted my earlier comment, sorry for the confusion :)

**Pull request merged**
